### ISSUE TITLE
4 - Database set up

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#11]
## Value statement - a requirement, not a solution
As a **user**
I need **a database**
So that **I can access my data from anywhere.**

## Description (Text, Scribble, Wireframe, Design)
my events will be saved like this in the MongoDB "bockwursts" collection:

{"_id":{"$oid":"62722430300d98e045f74074"},
"titel":"Dumplings Party","text":"Wollen wir mal wieder zusammen Dumplings bei mir Zuhause machen?",
"date":"13-06-2022",
"time":"17:30",
"location":"Harvestehude, Hamburg",
"confirm":false}

## Acceptance criteria
- [ ] all saved data by mongodb will be fetched and show on the home page.
- [ ] if the data cannot be fetched, an alert on the home page will be showed.

## Tasks
- [ ] set up mongodb
- [ ] create some json data on mongodb
- [ ] implement a connection to mongodb
- [ ] install env to hide the key from mongodb
- [ ] fetch data from mongodb to home page
- [ ] add error handling at the end

## Size
medium

**Comment by CJAkkuec** [comment]
Looking good, a couple of minor notes:

```
{"_id":{"$oid":"62722430300d98e045f74074"},
"titel":"Dumplings Party","text":"Wollen wir mal wieder zusammen Dumplings bei mir Zuhause machen?",
"date":"13-06-2022",
"time":"17:30",
"location":"Harvestehude, Hamburg",
"confirm":false}
```

`{"_id":{"$oid":"62722430300d98e045f74074"}`
I'm a little confused by how you handle your ids. Is there any reason for why it's an object inside an object?

`"location":"Harvestehude, Hamburg",`
I'd probably suggest you should do area code (PLZ) and city name, like: "12345 Example-City". This way the data can be re-purposed if you ever want to include a map, etc.

`"confirm":false`
It'd read better if instead of `confirm`, it'd be `confirmed`. : )

**Comment by zengqiangHe** [comment]
Hi CJ, 
for the id: I've copied this from the mongoDB. I cannot understand this as well. I'd better change it here.
I have changed the location and confirm to confrimed ^^ Thanks.
