### ISSUE TITLE
5 - Save the data from form "Abstimmung Erstellen" to database Handle Form Submission to a MongoDB backend

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#13]
## Value statement - a requirement, not a solution
As a **user**
I want **to save my form data to the database**
So that **I can access my data from anywhere**

## Description (Text, Scribble, Wireframe, Design)
the object in the database should be saved like this:
{
    "_id": {
        "$oid": "627916b8691e0"
    },
    "text": "Wollen wir mal wieder zusammen Dumplings bei mir Zuhause machen?",
    "date": "2022-06-13",
    "time": "17:30",
    "location": "Harvestehude, Hamburg",
    "confirm": false,
    "title": "Dumplings Party"
}
## Acceptance criteria
- [ ] once the user click the "Erstellen" button, the data should be post to mongoDB.
- [ ] the new created data from the form will be loaded on the home page as an event.
- [ ] if there's a problem by saving data, an error message will be showed.

## Tasks
- [ ] set up the database collection "bockwursts"
- [ ] implement POST 

## Size
Small

**Comment by zengqiangHe** [comment]
Hi, to be honest, I have no idea how to visualise this process, do you have  any tips for me? It's actually backend. I did some research on internet, I just followed the steps there to implement this process: https://medium.com/create-a-clocking-in-system-on-react/handle-form-submissions-in-react-to-a-mongodb-backend-a90cac7c81e9
