### ISSUE TITLE
6 - Create a Name Prompt page to save name to local storage

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#14]
## Value statement - a requirement, not a solution
As a **user**
I need **a page to save my name to local storage**
So that ** to save the stored data across browser sessions**

## Description (Text, Scribble, Wireframe, Design)

The snippet for local storage should be implemented like this:

localStorage.setItem('myCat', 'Tom');

## Acceptance criteria
- [ ] the name of the user is required, otherwise an error will be showed and the user cannot use the app further.
- [ ] once the user click "Weiter" button, the name will be saved to local storage and user wille be redirect to home page.

## Tasks
- [ ] create a form to let user giving name
- [ ] implement local storage to save data (name)

## Size
Small

**Comment by mpagels** [comment]
I argued to do that, because the backend is too big and for protoyping localStorage is enough for now.
