### ISSUE TITLE
8 - Create an Invitation Link page

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#19]
## Value statement - a requirement, not a solution
As a **user**
I need **an invitation Link **
So that **I can copy the link to invite friends to vote**

## Description (Text, Scribble, Wireframe, Design)
<img width="795" alt="Screenshot 2022-05-16 at 21 57 24" src="https://user-images.githubusercontent.com/100590592/168672158-d3998136-219b-4705-826b-eee49baaa225.png">

## Acceptance criteria
- [ ] once the form submitted, the user will be redirected to the "Einladung teilen" page.
- [ ] the endpoint of the link should be the id of the created event from MongoDB
- [ ] the user can see the whole link in the link box.
- [ ] once the user click the "Link kopieren" button, the link will be saved to clipboard and the user will be redirected to home page.
- [ ] a success message "Link kopiert!" will be displayed after copying url to clipboard.
- [ ] users will be redirected to the vote (BockWurst) page with the copied link.

## Tasks
- [ ] implement the react router to build a connection between the form and the "Einladung teilen" page.
- [ ] use the useLocation to get the id from the mongoDB
- [ ] add the clipboard function for the button to copy the invitation link.
- [ ] add a success message "Link kopiert!".

## Size
(Small, medium, large)
