### ISSUE TITLE
Edit Event Card 

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#22]
## Value statement - a requirement, not a solution
As a **user**
I need **an edit function**
So that **I will be able to update my events.**

## Description (Text, Scribble, Wireframe, Design)
![Screenshot 2022-05-22 at 16 51 15](https://user-images.githubusercontent.com/100590592/169701390-ac0e5750-4cc3-438e-aea6-8b178fda5072.png)

## Acceptance criteria
- [ ] once the user click the edit (pen) bottom on the top right, the user will be redirected to the edit page
- [ ] edit page was filled with information, which the user has already created. User can update the old information.
- [ ] once user click the update button on the bottom, the user will be redirected to the home page, and the updated event will be showed on the home page.

## Tasks
- [ ] create an edit with a pen icon for the event card.
- [ ] copy the create form and make some slightly changes, DRY.
- [ ] create a new react router for the edit page. like with the endpoint /edit

## Size
Small
