### ISSUE TITLE
Delete Event Card

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#23]
## Value statement - a requirement, not a solution
As a **user**
I need **a delete function**
So that **I can delete old events.**

## Description (Text, Scribble, Wireframe, Design)
![Screenshot 2022-05-22 at 16 51 15](https://user-images.githubusercontent.com/100590592/169701765-9c483686-dd6e-4cb4-affc-7243b50b0a76.png)

## Acceptance criteria
- [ ] user can delete event with a delete button on the top right of the card.

## Tasks
- [ ] create a delete button on the top right of the card.
- [ ] create some logic to find a right id, to make sure to delete a right card.

## Size
Small
