### ISSUE TITLE
Card Component on the home (Anstehend) page 

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#4]
## Value statement - a requirement, not a solution
As a **user**
I need **a home page**
So that **I can check how many events I have already voted and saved.**

## Description (Text, Scribble, Wireframe, Design)

![Screenshot 2022-04-27 at 11 45 17](https://user-images.githubusercontent.com/100590592/165491068-21d785d1-805b-44d2-acaa-fb5b38902e04.png)

## Acceptance criteria
- [ ] the colour of cards is not important yet
- [ ] there should be two icons ( calendar and location) in the card
- [ ] all rounded corners.

## Tasks
- [ ] create a card component with following contents: Title(Titel), Description(Beschreibung), location(Ort), date and time (Datum & Uhrzeit)
- [ ] give the cards simple style: width, height, padding and border radius. 
## Size
Small

**Comment by PReichetanz** [comment]
- value statement: "...how many events there will be" (or similar; you do not have the vote and save function yet ;)
- Description: You should not display the header ("BockWurst"), the "Anstehend" and "Übersicht" tags and the navigation since they are not part of the story.
- acceptance criteria / tasks: You should write down where the fake initialData for the Cards come from and what the structure of these data will be, for example:
```
const initialData = [
{ title: "Dumplings Party",
text: "Wollen wir mal wieder zusammen Dumplings bei mir Zuhause machen?",
date: [some date type here],
location: [location structure here]
}]
```

**Comment by CJAkkuec** [comment]
Looking good! My only note would be that if something's not important, it's not an acceptance criteria. ;)
