### ISSUE TITLE
Form (Erstllen) page

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#5]
## Value statement - a requirement, not a solution
As a **user**
I need **a form with three input fields and time&date picker. **
So that **I can type title of the occasion, a detailed description, the location and select time and date.**

## Description (Text, Scribble, Wireframe, Design)
![Screenshot 2022-04-27 at 11 28 33](https://user-images.githubusercontent.com/100590592/165489254-1d862d18-7f71-4fdf-8300-58d3cf663600.png)

## Acceptance criteria
- [ ] in the input field should consider adding a placeholder text to add an additional clue as to what kind of information the users are able to look up.
- [ ] remember of adding additional space between the three components. This one's pretty important, especially if the target audience includes a large spectrum of ages - not everyone has nimble fingers :)
- [ ] use contrast to the advantage. White text on a dark background - higher contrast. Dark text on a white background = better legibility. Reduced text opacity = less important hierarchy element or an inactive state.
- [ ] line height: WCAG recommendations is 1.5x of my font size. iOS type-scale guidelines (1.2x -1.4x).
- [ ] all rounded corners.
- [ ] show a calendar for date selection
- [ ] allow typing a desired date in the text field
- [ ] allow clicking on a desired date in the calendar in order to select a date
- [ ] the selected date appears in the text field and is indicated in the calendar

## Tasks
- [ ] create a header
- [ ] create a form with three input fields
- [ ] create a time and date picker
- [ ] create a submit button (Erstellen) without function
- [ ] create a navigation bar, so that the user can go back to the home page.

## Size
Medium

**Comment by PReichetanz** [comment]
## value statement:
   - check the ** format, there is a bug in your .md file
   - "so that I can add new data" would be fine, the exact kind of data will be explained below.
## acceptance criteria:
   - placeholder text: Which one exactly? As it can be seen in the image above? Please be clear about that here.
   - additional space: how much exactly?
   - contrast: Which ratio is acceptable, which is not? Be clear.
   - What about the navigation: Where does it come from? You need to add it here and under Tasks below.
   - Where do the data from submitting the form go? 

 ## Tasks:
   - I would outsource the header ("BockWurst") to another story, you don't need it here for your form.
   - Why does the submit button not have a function? That's not acceptable!

**Comment by CJAkkuec** [comment]
Looking good!

_"allow **typing** a desired date in the text field"_
I'd argue this wouldn't be part of the MVP, seeing as how it might give you more trouble than it's worth. Using the default date picker should serve you just fine for the time being. : )
