### ISSUE TITLE
3 - Overview (Übersicht) page

### ISSUE THREAD

**Issue by zengqiangHe** [zengqiangHe/capstone-project#7]
## Value statement - a requirement, not a solution
As a **user**
I need **a overview page**
So that **I can see the events I have already created and get some information like the amounts of participants**

## Description (Text, Scribble, Wireframe, Design)

![Screenshot 2022-04-27 at 20 59 46](https://user-images.githubusercontent.com/100590592/165604898-6c3d49c5-bd2d-478c-b40c-fdebbdd3342a.png)

## Acceptance criteria
- [ ] when the user click the "weiteren Personnen" should show more participants  under the card.
- [ ] when the user click the icon at the top on the right should have the function to edit or delete the event.

## Tasks
- [ ] create a category bar for "Anstehend" and "Übersicht" under the Header to show current page. The user can switch to home page once click "Anstehend" or the home icon in the navigation bar at the bottom of the app.
- [ ] create fake initial data for the cards and show the cards once user go to the page.
- [ ] create a fake function for the icon at the top on the right of the card, the real function will be create at the next step.

## Size
(medium)

**Comment by CJAkkuec** [comment]
-  when the user click the "weiteren Personnen" should show more participants under the card.
-  when the user click the icon at the top on the right should have the function to edit or delete the event.

-  create fake initial data for the cards and show the cards once user go to the page.

I think this would be part of the card component. :) (I'm pretty sure it already is.)

- create a fake function for the icon at the top on the right of the card, the real function will be create in the next step.

I'm not sure this step is necessary. The functionality of the dot-icon can be its own user story, as well. :) Although I feel like it might still be part of the card component itself.

As a general note: The basic concept of the overview page is to simply display data. You'd display the card component here, and sort according to 'Übersicht' and 'Anstehend'.

**Comment by zengqiangHe** [comment]
Hi CJ, thanks for your comment! I have planed to show my edit icon and the participants on this page, because there is still a home page. Only the user, who created events can see the card on this page. It might be not the same card component on the home page, because the user cannot edit or delete the card event on the home page. By the way, I've got an opinion from Martin that the dot icon should be changed to two buttons (edit and delete), which would be easier to implement for this moment.
